install:
  - 'git clone https://github.com/git-ftp/git-ftp.git'
  - 'cd git-ftp'
  - 'git checkout 1.1.0'
  - 'sudo make install'

script:
  - 'git clone https://github.com/compwj/travis-ci-deploy-ftp.git'
  - 'dir'
  - 'cd travis-ci-deploy-ftp'
  - 'git ftp push --user $FTP_USER --passwd $FTP_PASSWORD ftp://alpha.webreinvent.com/public_html'